### ISSUE TITLE
Docker not running after upgrade to v1.9.2

### ISSUE THREAD

**Issue by MattKobayashi** [burmilla/os#108]
**BurmillaOS Version: (ros os version)**
v1.9.2

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Baremetal

**Which processor architecture you are using?**
x86_64

**Do you use some extra hardware? (GPU, etc)?**
No

**Which console you use (default, ubuntu, centos, etc..)**
Default

**Do you use some service(s) which are not enabled by default?**
ZFS

**Have you installed some extra tools to console?**
No

**Do you use some other customizations?**
No

**Please share copy of your cloud-init (remember remove all sensitive data first)**
```yaml
hostname: <removed>
rancher:
  environment:
    EXTRA_CMDLINE: /init
  modules:
  - ""
  network:
    interfaces:
      eth0:
        addresses:
        - <removed>
        - <removed>
        dhcp: false
        dns:
          nameservers:
          - 1.1.1.1
          - 1.0.0.1
          - 2606:4700:4700::1111
          - 2606:4700:4700::1001
          override: true
          search:
          - <removed>
        gateway: <removed>
        gateway_ipv6: <removed>
        pre_up:
        - echo 0 > /proc/sys/net/ipv6/conf/eth0/accept_ra
  services_include:
    kernel-extras: true
    kernel-headers: false
    kernel-headers-system-docker: true
    zfs: true
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
  sysctl:
    net.core.netdev_budget_usecs: 20000
  upgrade:
    url: https://raw.githubusercontent.com/burmilla/releases/v1.9.x/releases.yml
runcmd:
- wget https://github.com/docker/compose/releases/download/1.29.1/docker-compose-Linux-x86_64 -O /usr/bin/docker-compose
- chmod +x /usr/bin/docker-compose
ssh_authorized_keys:
- <removed>
```

The Docker process doesn't seem to be running after upgrading to v1.9.2. `docker ps` returns the following:
```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/json: dial unix /var/run/docker.sock: connect: permission denied
```

`sudo docker ps` is similar:
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

A reboot doesn't fix the issue.
