### ISSUE TITLE
Possibility to set the default address pool

### ISSUE THREAD

**Issue by jokay** [burmilla/os#112]
**BurmillaOS Version: (ros os version)**

[1.9.2](https://github.com/burmilla/os/releases/tag/v1.9.2)

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**

VM on [ProxmoxVE](https://www.proxmox.com/en/proxmox-ve)

**Which processor architecture you are using?**

amd64

**Do you use some extra hardware? (GPU, etc)?**

no

**Which console you use (default, ubuntu, centos, etc..)**

default

**Do you use some service(s) which are not enabled by default?**

- qemu-guest-agent
- crontab

**Have you installed some extra tools to console?**

no

**Do you use some other customizations?**

no

---

We need to be able to set the default address pool via **cloud-config.yml**, see [here](https://serverfault.com/a/936255) and [here](https://github.com/moby/moby/pull/29376).

Do you think it's possible to provide this?

**Comment by olljanat** [comment]
`extra_args` should works. Look: https://burmillaos.org/docs/configuration/docker/#example-using-extra_args-for-setting-mtu

**Comment by jokay** [comment]
thx, will try.

**Comment by jokay** [comment]
@olljanat this seems not to work.

```yml
hostname: "test"

rancher:
  docker:
    extra_args: [--default-address-pools, "[{\"base\":\"172.20.0.0/16\",\"size\":24}]"]
  services_include:
    qemu-guest-agent: true
```

```sh
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Any other idea?

**Comment by jokay** [comment]
https://straz.to/2021-09-08-docker-address-pools/

**Comment by jokay** [comment]
Seems unsupported?

```yml
sudo ros config set rancher.docker.extra_args [--default-address-pools,"scope=local,base=172.17.0.0/12,size=20"]
```
```yml
#cloud-config
rancher:
  docker:
    extra_args:
    - --default-address-pools
    - scope=local
    - base=172.17.0.0/12
    - size=20
```
```sh
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by jokay** [comment]
This seems to finally work.

```yml
#cloud-config
rancher:
  docker:
    extra_args: [--default-address-pool,"base=172.17.0.0/12,size=20"]
```
