### ISSUE TITLE
System CA certificates don't include new Let's Encrypt CA (ISRG Root X1)

### ISSUE THREAD

**Issue by alesnav** [burmilla/os#127]
Hello there,

It seems that system SSL root certificates have not been updates to include the new Let's Encrypt root CA, as per stated in the logs whener I try to deploy Elasticsearch after a reboot (it was working without any issue before upgrading from os:v1.9.0 to os:1.9.3, but only because the Elasticsearch image was fixed to a specific version and it was available locally in BurmillaOS nodes).

**Log showing the error:**
```
[rancher@rancher01 ~]$ docker pull docker.elastic.co/elasticsearch/elasticsearch:7.14.0
Error response from daemon: Get "https://docker.elastic.co/v2/": x509: certificate signed by unknown authority
```

**Current CA associated to docker.elastic.co site:**
ISRG Root X1 (available from https://letsencrypt.org/certificates/)

**BurmillaOS Version: (ros os version)**
burmilla/os:v1.9.3

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VMware ESXi

**Which processor architecture you are using?**
x86_64

**Do you use some extra hardware? (GPU, etc)?**
No

**Which console you use (default, ubuntu, centos, etc..)**
It seems that only default is available

**Do you use some service(s) which are not enabled by default?**
No

**Have you installed some extra tools to console?**
No

**Do you use some other customizations?**
No

**Please share copy of your cloud-init (remember remove all sensitive data first)**
```yaml
hostname: rancher01
mounts:
- - x.y.z.a:/data
  - /nas
  - nfs
  - port=2049,proto=tcp,nolock,vers=3
rancher:
  docker:
    engine: docker-20.10.9
  environment:
    EXTRA_CMDLINE: /init
  modules:
  - ip_vs
  network:
    dns:
      nameservers:
      - a.b.c.y
      search:
      - domain.local
    interfaces:
      eth0:
        address: a.b.c.d/24
        dhcp: false
        gateway: a.b.c.x
        mtu: 1450
  services_include:
    open-vm-tools: true
    volume-nfs: true
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
  sysctl:
    net.ipv4.ip_nonlocal_bind: 1
    net.ipv6.ip_nonlocal_bind: 1
    vm.max_map_count: 262144
  upgrade:
    url: https://raw.githubusercontent.com/burmilla/releases/v1.9.x/releases.yml
ssh_authorized_keys:
- ssh-rsa ......
- ecdsa-sha2-nistp521 ......
```
