### ISSUE TITLE
Failed to boot after upgrade from 2.0.0-rc2 to 2.0.0

### ISSUE THREAD

**Issue by ghysler** [burmilla/os#175]
**BurmillaOS Version: 2.0.0-rc2

**Where are you running BurmillaOS?** Proxmox

**Which processor architecture you are using?** x64

**Do you use some extra hardware? (GPU, etc)?** no.

**Which console you use (default, ubuntu, centos, etc..)** Default.

**Do you use some service(s) which are not enabled by default?** qemu-guest-agent

**Have you installed some extra tools to console?** No.

**Do you use some other customizations?** No.

**Please share copy of your cloud-init (remember remove all sensitive data first)**
```yaml
# sudo ros config export output
hostname: a.b.c
rancher:
  console: default
  docker:
    engine: docker-20.10.22
  environment:
    EXTRA_CMDLINE: /init
  network:
    interfaces:
      eth0:
        address: x.x.x.x/24
        gateway: x.x.x.x
  services:
    console:
      labels:
      - io.docker.compose.rebuild=false
      - io.rancher.os.after=network
      - io.rancher.os.console=default
      - io.rancher.os.scope=system
  services_include:
    qemu-guest-agent: true
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
  upgrade:
    url: https://raw.githubusercontent.com/burmilla/releases/v2.0.x/releases.yml
ssh_authorized_keys:
- ssh-rsa pubkey
```

After upgrading to the final version of 2.0.0, BurmillaOS will not completely boot. I am unable to reach the VM via network, but also the console is not functional (no login prompt). If I select to boot 2.0.0-rc2 from GRUB, it boots successfully. Do I have to perform additional steps when upgrading from rc2?

Screenshot of console after booting 2.0.0 final attached.

![Clipboarder 2024 03 22](https://github.com/burmilla/os/assets/16139880/95e82c74-bdc4-46e0-93ed-26c059cd1071)
