### ISSUE TITLE
CRITICAL: x509: certificate has expired or is not yet valid (all versions affected)

### ISSUE THREAD

**Issue by ArgonV** [burmilla/os#176]
**NOTE!!!** Fix available in https://github.com/burmilla/os/releases/tag/v2.0.1

---
**BurmillaOS Version: (ros os version)** v2.0 release

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)** docker-machine on vSphere

**Which processor architecture you are using?** x86

**Do you use some extra hardware? (GPU, etc)?** No

**Which console you use (default, ubuntu, centos, etc..)**

**Do you use some service(s) which are not enabled by default?** No

**Have you installed some extra tools to console?** vmware-tools

**Do you use some other customizations?**

**Please share copy of your cloud-init (remember remove all sensitive data first)**
```
#cloud-config
runcmd:
- ["sudo", "mkfs.ext4", "/dev/sda"]
- ["sudo", "ros", "install", "-d", "/dev/sda", "--no-reboot", "-c", "/var/lib/rancher/conf/cloud-config.yml"]
- ["sudo", "reboot"]
rancher:
  docker:
    engine: docker-26.0.1
  sysctl:
    vm.max_map_count: 2621444
  state:
    autoformat:
    - /dev/sda
    - /dev/vda
    dev: LABEL=RANCHER_STATE
    wait: true
```

When I first boot up, and it pulls vmware tools ISO: I'm getting this message:

ros-sysinit:error: Failed Starting open-vm-tools
Status : error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/29/<stringUUID>
x509: certificate has expired or is not yet valid, Code: 1

When I go to the site and look at the cert in my web browser, it was renewed Wed, 10 Apr 2024 23:38:51 GMT
