### ISSUE TITLE
Custom services fail to create in 2.0.x

### ISSUE THREAD

**Issue by skobkars** [burmilla/os#198]
Upgraded my Proxmox-based (7.4-19) VM running BurmillaOS 1.9.5 to 2.0.2:

```
# ros --version
version v2.0.2 from os image burmilla/os:v2.0.2
```
and having issues with custom services.

I have a cron task successfully running before, but the same service fails to start on v2.0.2.

And it seems that it has nothing to do with the service itself, as even the simplest Nginx test:

```
# cat /var/lib/rancher/conf/test.yml
test:
  image: nginx
  restart: always
```

gets enabled Okay:

```
# ros service enable /var/lib/rancher/conf/test.yml 
INFO[0000] Service test using local image nginx
```

but fails to start:
```
# ros service up test
INFO[0000] Project [os]: Starting project               
INFO[0001] [0/22] [test]: Starting                      
INFO[0001] Waiting for Docker at unix:///var/run/docker.sock 
INFO[0001] Waiting for Docker at unix:///var/run/docker.sock 
INFO[0001] Waiting for Docker at unix:///var/run/docker.sock 
INFO[0001] Waiting for Docker at unix:///var/run/docker.sock 
INFO[0002] Waiting for Docker at unix:///var/run/docker.sock 
INFO[0004] Waiting for Docker at unix:///var/run/docker.sock 
INFO[0006] Waiting for Docker at unix:///var/run/docker.sock 
INFO[0008] Waiting for Docker at unix:///var/run/docker.sock 
...
```

Switching back to 1.9.5 resolves the problem and the service is running again, so this is something with 2.0.2 or 2.0.x

**Comment by olljanat** [comment]
Is the user Docker running and example `docker version` command working?

If not, try switch to latest Docker version with `ros engine switch`

If that does not help then provide `ros config export` content?

**Comment by skobkars** [comment]
Yes, all the regular user Docker containers and Docker swarm services run just fine, only the OS custom services are not. Should probably have mentioned that my user Docker is running in swarm mode, btw.

```
$ docker version
Client:
 Version:           27.5.0
 API version:       1.47
 Go version:        go1.22.10
 Git commit:        a187fa5
 Built:             Mon Jan 13 15:23:50 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.5.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.10
  Git commit:       38b84dc
  Built:            Mon Jan 13 15:25:13 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.25
  GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc:
  Version:          1.2.4
  GitCommit:        v1.2.4-0-g6c52b3f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Here is the ```ros config export``` output:

```
hostname: xxx.xxx.xx
mounts:
- - LABEL=volumes
  - /home/rancher/volumes
  - ext4
  - ""
rancher:
  disable:
  - password
  - autologin
  docker:
    engine: docker-27.5.0
    extra_args:
    - --mtu
    - 1460
  environment:
    EXTRA_CMDLINE: /init
  network:
    dns:
      nameservers:
      - xxx.xxx.xxx.xxx
      - xxx.xxx.xxx.xxx
      search:
      - xxx.xx
      - xx.xxx.xx
    interfaces:
      eth0:
        address: xxx.xxx.xxx.xxx/xx
        dhcp: false
        gateway: xxx.xxx.xxx.xxx/xx
        mtu: 1460
      eth1:
        address: 192.168.xxx.xxx/24
        dhcp: false
        gateway: 192.168.xxx.xxx
        mtu: 1460
  resize_device: /dev/sda
  services_include:
    /var/lib/rancher/conf/certbot.yml: true
    container-cron: true
    qemu-guest-agent: true
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
  system_docker:
    extra_args:
    - --mtu
    - 1460
  upgrade:
    url: https://raw.githubusercontent.com/burmilla/releases/v2.0.x/releases.yml
ssh_authorized_keys:
- ssh-rsa AAAA...
- ssh-rsa AAAA...
write_files:
- content: |+
    #!/bin/bash
    if [ -d /var/lib/docker/swarm ]; then mkdir -p /home/rancher/volumes/swarm && mount -o bind /home/rancher/volumes/swarm /var/lib/docker/swarm; fi
    wait-for-docker
    # Init swarm
    [[ $(docker info | awk '/Swarm:/{print $2}') == "inactive" ]] && docker swarm init --force-new-cluster --advertise-addr 192.168.242.23:2377
    # Add overlay network
    [[ $(docker network ls | awk '/my-swarm/{print $2}') != "overlay" ]] && docker network create -d overlay --attachable --subnet=172.23.0.0/16 my-swarm
    /home/rancher/volumes/scripts/onboot
  owner: root
  path: /etc/rc.local
  permissions: "0755"
- content: |+
    PATH=$PATH:$HOME/volumes/scripts
    function ll () { ls -al $@; }
    function htop () { (docker run --rm --pid=host -it 127.0.0.1:5000/htop:latest "$@" ) }
    function git () { (docker run -u $(id -u):$(id -g) -ti --rm -v ${HOME}:${HOME} -v /etc:/etc -v $(pwd):/git -v $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK 127.0.0.1:5000/git "$@") }
  owner: rancher
  path: /home/rancher/.profile
  permissions: "0644"
- content: |+
    certbot:
      image: 127.0.0.1:5000/certbot
      volumes:
        - /home/rancher/volumes/scripts/certbot/:/hooks:ro
        - /home/rancher/volumes/scripts/certbot/letsencrypt:/etc/letsencrypt
        - /home/rancher/volumes/scripts/nginx/.well-known:/usr/share/nginx/html/.well-known
        - /usr/bin/docker:/usr/bin/docker:ro
        - /var/run/docker.sock:/var/run/docker.sock
      command: |
        renew
        --post-hook=/hooks/reload-hook
      labels:
        cron.schedule: "0 0 4,16 * * ?"
  owner: root
  path: /var/lib/rancher/conf/certbot.yml
  permissions: "0644"
```

Tried BurmillaOS v2.0.0 and v2.0.1 and the custom services actually work, so something broke in the v2.0.2.

Switching engine within v2.0.2 doesn't help and _neither_ of following combinations work: 

```
# ros os version
v2.0.2
# ros engine list
disabled docker-27.4.1
current  docker-27.5.0 (latest)
```

```
# ros os version
v2.0.2
# ros engine list
current  docker-27.4.1
disabled docker-27.5.0 (latest)
```

v2.0.1 doesn't work with docker-27.4.1 either:

```
# ros os version
v2.0.1
# ros engine list
...
current  docker-27.4.1
```

========================

It appears that the latest version of Docker that actually work with custom services is 24.0.9, as this combination runs fine:

```
# ros os version
v2.0.1
# ros engine list
...
current  docker-24.0.9
```
