### ISSUE TITLE
Cluster health check failed: cluster agent is not ready problem

### ISSUE THREAD

**Issue by Shaggy84675** [burmilla/os#46]
**BurmillaOS Version: (ros os version)**
v1.9.0

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**
ESXi-6.5.0

**Which processor architecture you are using?**
x64

**Do you use some extra hardware? (GPU, etc)?**
No

**Which console you use (default, ubuntu, centos, etc..)**
default

**Do you use some service(s) which are not enabled by default?**
No

**Have you installed some extra tools to console?**
No

**Do you use some other customizations?**
No

**Please share copy of your cloud-init (remember remove all sensitive data first)**
```yaml
rancher:
  environment:
    EXTRA_CMDLINE: /init
  services_include:
    open-vm-tools: true
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
ssh_authorized_keys:
- ssh-rsa
```

Hello,

I've tried to install a clean version of latest Rancher, but I'm still getting error:  Cluster health check failed: cluster agent is not ready when adding a new custom cluster. Any idea where could be a problem? I've also tried to install it on Debian and that was without any problems.

Thank you
