### ISSUE TITLE
Upgrade from rancher/os to burmilla/os incomplete

### ISSUE THREAD

**Issue by zimme** [burmilla/os#48]
**BurmillaOS Version: (ros os version)**
1.9.0
**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal
**Which processor architecture you are using?**
x86-64
**Do you use some extra hardware? (GPU, etc)?**
GPU, HBA
**Which console you use (default, ubuntu, centos, etc..)**
default
**Do you use some service(s) which are not enabled by default?**
zfs,kernel-header,kernel-extras
**Have you installed some extra tools to console?**
lm-sensors
**Do you use some other customizations?**
Nope
**Please share copy of your cloud-init (remember remove all sensitive data first)**
```yaml
#cloud-config
hostname: storage
rancher:
  modules:
  - coretemp
  - nct6775
  - sata_sil
  services_include:
    kernel-extras: true
    kernel-headers: true
    zfs: true
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
ssh_authorized_keys:
    ......
```

I just upgraded my server from rancher/os 1.5.6 to burmilla/os 1.9.0 and things went smoothly in general. However I realized that the config option "rancher.repositories.core.url" wasn't upgraded to burmilla/os-services so I had to do that manually.

Just wanted to give you a heads up that it's either a step missing in the upgrade guide or that something that should be taken care of during upgrade isn't happening as expected.
