### ISSUE TITLE
Update rsync

### ISSUE THREAD

**Issue by EVOTk** [burmilla/os#62]
Hello,

Is it possible to update rsync to the latest version?
Currently BurmillaOS uses version 3.1.3 from 2018. The latest version is 3.2.3 https://rsync.samba.org/.

Thx
------

**BurmillaOS Version: (ros os version)** v2.0.0-beta3

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)** Proxmox VM

**Which processor architecture you are using?** AMD64

**Which console you use (default, ubuntu, centos, etc..)** default

**Please share copy of your cloud-init (remember remove all sensitive data first)**
```yaml
rancher:
  environment:
    EXTRA_CMDLINE: /init
  network:
    interfaces:
      eth0:
        address: 192.168.2.39/24
        dhcp: false
        gateway: 192.168.2.1
        mtu: 1500
  services_include:
    docker-compose: true
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
ssh_authorized_keys:
- XXX
```
